name: skein_color_convert
description: A color conversion library for Dart. It converts all ways between rgb, hsl, hsv, hwb, cmyk, ansi, ansi16, hex strings, and CSS keywords (will round to closest).
version: 1.0.2
repository: https://github.com/SathishSkein888/skein_color_convert.git
homepage: https://github.com/SathishSkein888/skein_color_convert.git

environment:
  sdk: '>=2.12.1 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
